version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore(deps):"
- package-ecosystem: docker
  directory: "/."
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore(deps):"
- package-ecosystem: gitsubmodule
  directory: "/snapraid/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  commit-message:
    prefix: "feat(snapraidf):"