on: pull_request

name: Builds

jobs:

  dockerbuild:

    name: Docker
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
    -
      name: extract tag
      id: vars
      run: |
        git fetch --prune --unshallow
        echo ::set-output name=snapraid_version::"$(cd snapraid/ && git describe --abbrev=0)"
    -
      name: docker build
      run: docker build . --file Dockerfile --tag image:${{ steps.vars.outputs.snapraid_version }}
