on:
  push:
    branches:
    - master

name: Publish Image
jobs:
  dockerpush:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v2
      with:
        submodules: true
    -
      name: extract tag
      id: vars
      run: |
        git fetch --prune --unshallow
        echo ::set-output name=version::"$(cd snapraid/ && git describe --abbrev=0)"
    - 
      run: echo "Pushing version ${{ steps.version.outputs.version }}"
    - 
      name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@3.01
      with:
        registry: ghcr.io
        name: "ghcr.io/ironpeakservices/iron-snapraid:${{ steps.version.outputs.version }}"
        username: hazcod
        password: ${{ secrets.PACKAGE_TOKEN }}
    - 
      name: Create GitHub release
      uses: actions/create-release@v1.1.4
      with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: iron-snapraid
          draft: false
          prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}